# Generated by Django 4.1.4 on 2023-03-23 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fazenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FichaOrdenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "data",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de Ordenhas",
                "verbose_name_plural": "Fichas de Ordenhas",
            },
        ),
        migrations.CreateModel(
            name="Vaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("nome", models.CharField(max_length=255)),
                (
                    "prefixo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TE", "Transferência Embrionária"),
                            ("AM", "Amojada"),
                            ("PRI", "Primeira Alguma Coisa"),
                            ("DESC", "Descarte"),
                            ("LI", "Lítio"),
                        ],
                        max_length=31,
                        null=True,
                    ),
                ),
                (
                    "nome_ideagri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "fazenda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fazenda.fazenda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[("M", "Manhã"), ("T", "Tarde")], max_length=1
                    ),
                ),
                ("peso", models.FloatField()),
                ("data", models.DateField(blank=True, null=True)),
                (
                    "ficha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fazenda.fichaordenha",
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fazenda.vaca"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FotoOrdenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.TextField(blank=True, null=True)),
                ("original", models.ImageField(upload_to="")),
                ("lines", models.ImageField(blank=True, null=True, upload_to="")),
                ("dewarped", models.ImageField(blank=True, null=True, upload_to="")),
                ("bbox", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "ficha",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fazenda.fichaordenha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de Ordenhas",
                "verbose_name_plural": "Fotos de Ordenhas",
            },
        ),
    ]
