# Generated by Django 4.1.4 on 2023-03-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fazenda", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fotoordenha",
            name="ficha",
        ),
        migrations.RemoveField(
            model_name="ordenha",
            name="ficha",
        ),
        migrations.RemoveField(
            model_name="ordenhadetectada",
            name="ficha",
        ),
        migrations.AddField(
            model_name="ordenhadetectada",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fazenda.fotoordenha",
            ),
        ),
        migrations.DeleteModel(
            name="FichaOrdenha",
        ),
    ]
