# Generated by Django 4.1.4 on 2023-03-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "image_labelling_tool",
            "0009_alter_labelclass_id_alter_labelclasscolour_id_and_more",
        ),
        ("fazenda", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fotoordenha",
            name="points",
        ),
        migrations.AddField(
            model_name="fotoordenha",
            name="labels",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="image_labelling_tool.labels",
            ),
            preserve_default=False,
        ),
    ]
