# Generated by Django 4.1.4 on 2023-03-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fazenda", "0002_remove_fotoordenha_ficha_remove_ordenha_ficha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenha",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fazenda.fotoordenha",
            ),
        ),
    ]
