# Generated by Django 4.1.4 on 2023-03-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "image_labelling_tool",
            "0009_alter_labelclass_id_alter_labelclasscolour_id_and_more",
        ),
        ("fazenda", "0002_remove_fotoordenha_points_fotoordenha_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fotoordenha",
            name="labels",
        ),
        migrations.CreateModel(
            name="ImageWithLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                (
                    "labels",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="image_labelling_tool.labels",
                    ),
                ),
            ],
        ),
    ]
