# Generated by Django 4.1.4 on 2023-03-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "image_labelling_tool",
            "0009_alter_labelclass_id_alter_labelclasscolour_id_and_more",
        ),
        ("fazenda", "0003_remove_fotoordenha_labels_imagewithlabels"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotoordenha",
            name="labels",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original",
                to="image_labelling_tool.labels",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ImageWithLabels",
        ),
    ]
