# Generated by Django 4.1.4 on 2023-01-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0004_rename_fotos_fotoordenha_foto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotoordenha",
            old_name="foto",
            new_name="image",
        ),
    ]
