# Generated by Django 4.1.4 on 2023-03-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "image_labelling_tool",
            "0009_alter_labelclass_id_alter_labelclasscolour_id_and_more",
        ),
        ("fazenda", "0005_alter_fotoordenha_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labels",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("image_labelling_tool.labels",),
        ),
        migrations.AlterField(
            model_name="fotoordenha",
            name="labels",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original",
                to="image_labelling_tool.labels",
            ),
        ),
    ]
