# Generated by Django 4.1.4 on 2023-01-26 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0005_rename_foto_fotoordenha_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichaordenha",
            name="data",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
