# Generated by Django 4.1.4 on 2023-01-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0006_alter_fichaordenha_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichaordenha",
            old_name="foto_bbox",
            new_name="bbox",
        ),
        migrations.RenameField(
            model_name="fichaordenha",
            old_name="foto_linhas",
            new_name="linhas",
        ),
        migrations.RemoveField(
            model_name="fichaordenha",
            name="foto_original",
        ),
    ]
