# Generated by Django 4.1.4 on 2023-03-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0007_remove_fotoordenha_lines_alter_fotoordenha_labels"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vaca",
            unique_together={("numero", "nome")},
        ),
    ]
