# Generated by Django 4.1.4 on 2023-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0007_rename_foto_bbox_fichaordenha_bbox_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaordenha",
            name="bbox",
        ),
        migrations.RemoveField(
            model_name="fichaordenha",
            name="linhas",
        ),
        migrations.AddField(
            model_name="fotoordenha",
            name="bbox",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="fotoordenha",
            name="linhas",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
