# Generated by Django 4.1.4 on 2023-01-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fazenda",
            "0008_remove_fichaordenha_bbox_remove_fichaordenha_linhas_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotoordenha",
            old_name="image",
            new_name="original",
        ),
    ]
