# Generated by Django 4.1.4 on 2023-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0008_alter_vaca_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenha",
            name="nome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ordenha",
            name="numero",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
