# Generated by Django 4.1.4 on 2023-01-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0009_rename_image_fotoordenha_original"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotoordenha",
            old_name="original",
            new_name="image",
        ),
    ]
