# Generated by Django 4.2.7 on 2024-08-20 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fazenda", "0009_ordenhadetectada_prefixo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenhadetectada",
            name="prefixo",
        ),
    ]
