# Generated by Django 4.1.4 on 2023-03-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0009_ordenha_nome_ordenha_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoordenha",
            name="ficha",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fazenda.fichaordenha",
            ),
            preserve_default=False,
        ),
    ]
