# Generated by Django 4.2.7 on 2024-08-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0010_remove_ordenhadetectada_prefixo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoordenha',
            name='peso_balde',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordenha',
            name='peso_manha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ordenha',
            name='peso_tarde',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
