# Generated by Django 4.1.4 on 2023-03-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0010_alter_fotoordenha_ficha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoordenha",
            name="ficha",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotoordenha",
                to="fazenda.fichaordenha",
            ),
        ),
    ]
