# Generated by Django 4.1.4 on 2023-03-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0011_alter_fotoordenha_ficha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoordenha",
            name="labels",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fotoordenha",
                to="fazenda.labels",
            ),
        ),
    ]
