# Generated by Django 4.1.4 on 2023-03-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0012_alter_fotoordenha_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labels",
            options={"verbose_name": "Label Set", "verbose_name_plural": "Label Sets"},
        ),
        migrations.AlterField(
            model_name="fotoordenha",
            name="labels",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotoordenha",
                to="fazenda.labels",
            ),
            preserve_default=False,
        ),
    ]
