# Generated by Django 4.1.4 on 2023-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0013_alter_labels_options_alter_fotoordenha_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotoordenha",
            name="bbox_countour",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="fotoordenha",
            name="dewarped_countour",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
