# Generated by Django 4.1.4 on 2023-03-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0014_fotoordenha_bbox_countour_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotoordenha",
            old_name="bbox_countour",
            new_name="bbox_contour",
        ),
        migrations.RenameField(
            model_name="fotoordenha",
            old_name="dewarped_countour",
            new_name="dewarped_contour",
        ),
    ]
