# Generated by Django 4.1.4 on 2023-03-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0015_rename_bbox_countour_fotoordenha_bbox_contour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fotoordenha",
            name="bbox_contour",
        ),
        migrations.RemoveField(
            model_name="fotoordenha",
            name="dewarped_contour",
        ),
        migrations.AddField(
            model_name="fotoordenha",
            name="bounds",
            field=models.TextField(blank=True, null=True),
        ),
    ]
