# Generated by Django 4.1.4 on 2023-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0016_remove_fotoordenha_bbox_contour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenha",
            name="periodo",
        ),
        migrations.RemoveField(
            model_name="ordenha",
            name="peso",
        ),
        migrations.AddField(
            model_name="ordenha",
            name="nome_auto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ordenha",
            name="numero_auto",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordenha",
            name="peso_manha",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordenha",
            name="peso_manha_auto",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordenha",
            name="peso_tarde",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordenha",
            name="peso_tarde_auto",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
