# Generated by Django 4.1.4 on 2023-03-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0017_remove_ordenha_periodo_remove_ordenha_peso_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenha",
            name="peso_manha_auto",
        ),
        migrations.RemoveField(
            model_name="ordenha",
            name="peso_tarde_auto",
        ),
    ]
