# Generated by Django 4.1.4 on 2023-03-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0018_remove_ordenha_peso_manha_auto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenha",
            name="vaca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fazenda.vaca",
            ),
        ),
    ]
