# Generated by Django 4.1.4 on 2023-03-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0019_alter_ordenha_vaca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenha",
            name="numero_auto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ordenha",
            name="peso_manha",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ordenha",
            name="peso_tarde",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
