# Generated by Django 4.1.4 on 2023-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0020_alter_ordenha_numero_auto_alter_ordenha_peso_manha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenhaDetectada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=255, null=True)),
                ("nome", models.CharField(blank=True, max_length=255, null=True)),
                ("peso_manha", models.CharField(blank=True, max_length=255, null=True)),
                ("peso_tarde", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="ordenha",
            name="nome_auto",
        ),
        migrations.RemoveField(
            model_name="ordenha",
            name="numero_auto",
        ),
        migrations.AlterField(
            model_name="ordenha",
            name="peso_manha",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ordenha",
            name="peso_tarde",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
