# Generated by Django 4.1.4 on 2023-03-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fazenda", "0022_ordenhadetectada_ordenha"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenhadetectada",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fazenda.fichaordenha",
            ),
        ),
    ]
